### ISSUE TITLE
[BUG] Pf2e auras lagging with walls.

### ISSUE THREAD

**Issue by Gossetjr** [ironmonk88/monks-wall-enhancement#40]
I ran FTC and found that MWE was causing lag when I place a Mummy Pharaoh on the map. It has a 100ft aura. The pf2e discord knows there is an issue with module walls (wall height for example) and auras but they have no idea what it is.

Pathfinder2e version 6.3.1 and foundryvtt version 12 build 331

**Comment by CrackJackFlood** [comment]
I have been hunting for the cause of this lag for a while its existed at least since last september. Can confirm 100% when using auras in pf2e and this module is enabled during intiative rolls and during combat (intermittent) lag spikes will happen even on scenes with no walls.

Somthing in this module wierdly causes it.

**Comment by Crowguard** [comment]
@CrackJackFlood Can you try disabling the setting `Allow 1 Way Walls` and see if that fixes it?

**Comment by Crowguard** [comment]
After testing...its some kind of interaction between `Allow 1 Way Doors` and auras. Can replicate with the Mummy Pharaoh, and disabling the setting makes it behave as normal.

Couple of users reporting this is an issue in 5e as well when the setting is enabled and another module called CPR is enabled, but no idea what feature it has that causes this.

PF2 6.6.1
MWE 12.01

**Comment by ironmonk88** [comment]
Added code to make the function a little more efficient.
